# Generated by Django 3.0 on 2019-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_measurement', models.DateTimeField()),
                ('motor_rotations', models.DecimalField(decimal_places=3, max_digits=5)),
                ('temperature_1', models.DecimalField(decimal_places=3, max_digits=4)),
                ('temperature_2', models.DecimalField(decimal_places=3, max_digits=4)),
                ('current_draw', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
