# Generated by Django 3.0 on 2019-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
