# Generated by Django 3.0 on 2019-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0002_measurements_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
