# Generated by Django 3.0 on 2019-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0003_auto_20191213_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='current_draw',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='motor_rotations',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='temperature_1',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='temperature_2',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
