# Generated by Django 3.0.2 on 2020-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0004_auto_20191213_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='user_name',
            field=models.TextField(blank=True, max_length=35),
        ),
    ]
